Update installing-for-development.md
livepeer/docs pull request #138
Opened 2022-02-17 13:20 UTC by 0xB79

I had to install protobuf-compiler-grpc and golang-goprotobuf-dev to build from source on Ubuntu 20.04 using makefile.  Installing first fixed error "/bin/bash: protoc: command not found" protoc not found".  Installing second fixed error "protoc-gen-go: program not found or is not executable".

2022-02-17 22:20 UTC, hthillman requested changes
just one minor change, otherwise looks good!

2022-02-17 22:20 UTC, hthillman commented on docs/installation/install-livepeer/installing-for-development.md
> +apt-get update && apt-get -y install build-essential pkg-config autoconf git curl protobuf-compiler-grpc golang-goprotobuf-dev
I'm guessing that this isn't necessary on v16 and v18 of Ubuntu - could you keep the original command in place and specify that the update is necessary to make it work for v20?

2022-02-22 18:35 UTC, hthillman commented
@0xB79 did you see the comment here?

2022-02-23 12:46 UTC, 0xB79 commented
I did not initially see requested update.  I updated

2022-02-23 16:02 UTC, hthillman approved these changes

2022-02-23 16:02 UTC, merged